### ISSUE TITLE
Problem loading example data when pop structure module is active

### ISSUE THREAD

**Issue by covaruber** [Breeding-Analytics/bioflow#19]
Dear Angela, I wanted to let you know that Khaled, Ibnou and myself couldn't trace the problem exactly but when the population structure module is active it doesn't allow to load example datasets in other modules.

<img width="572" alt="Screenshot 2024-04-01 at 8 59 43 PM" src="https://github.com/Breeding-Analytics/bioflow/assets/27698022/0b57335a-2cdd-43c3-a5e1-d22488faa561">

Could you see if you are mimicking the same way to upload example datasets than in the other modules? Is something that does not happen in the local computers but the error is triggered once is deployed in the EBS or shiny servers. Sorry that I couldn't figure out what is it. I had to silence the module for now since we are trying a 100 people in India this week and we needed the participants to load the example datasets. Let me know if I can help in anything :)  

Cheers,
Eduardo

**Comment by RAngelaPG** [comment]
Hi Eduardo,

I check the code and review my notes about the variables names that I used and it does not match with any other module, I still made changes to some variables names, Could you check if the problem continues? please!

**Comment by covaruber** [comment]
Thanks Angela, I don't know which line made the job but now is working. Still, I was wondering if you can replace the ddextend library with any other package that can do a simular plot. It seems that this library overwrites methods of other libraries. Thanks a lot :)

**Comment by RAngelaPG** [comment]
The dendrogram no longer uses that library, in fact it is not called at all in the code, dendrogram use ggtree and ape library only.
