### ISSUE TITLE
Dependencies

### ISSUE THREAD

**Issue by covaruber** [Breeding-Analytics/bioflow#22]
Hi Angela, sorry to keep bothering you but I need another favor. For a shiny app to be stable we need to specify which packages have to be used, versions and where should be founded in the DESCRIPTION file. This is achieved running the following command lines (for example):

`usethis::use_package("gridExtra")`

for a package available on CRAN. The version specified will be the one available in your local. And for example:

`usethis::use_dev_package("cgiarBase", type = "Imports", remote = "Breeding-Analytics/cgiarBase")`

for a package available in GitHub but not on CRAN. If your needed packages is somewhere else please Google what would be the equivalent. It seems that your population structure needs packages like ape, agnes, gorree, etc. Please add those to the DECRIPTION file using the method above :)

Also please in the module do not call the library specifically unless is totally necessary. Please use the approach

`package::function()`

instead of

`library(package)`

to avoid that functions get overwritten between packages using the same names. Thanks in advance :)

**Comment by covaruber** [comment]
Thanks Angela, this is looking good :D I already merged the pull request.

I was wondering if you would consider making the MDS, Fst, and the other algorithms  inside the reactive of the run button. Currently, I noticed that if you move to the output tabs without clicking the run button still display the plots which means that the calculations occur inside the application. 

Maybe the way to achieve that is to have your functions in the cgiarBase package that take as input the data object and spit the required tables for the visualizations. Then the shiny app server has the reactive event for the run button and inside the calculations occur and the visualizations are displayed if the function ran well. What do you think?

Cheers,
Eduardo

**Comment by RAngelaPG** [comment]
Hi Eduardo,

Thank you!

About the run button. I don't know if I understand well, I did some changes in MDS, Fst and dendogram, but not all I can put in run button because I add some style parameters that can be change in the plots, so you suggest that I need to delete all these style parameters? or with the changes that I did is enough.

Best
Angela

**Comment by covaruber** [comment]
Hi Angela, I think we may need a call to clarify this but I can add some clarification points to the business rules :)

1) the data structure is a fixed one, we can only add to the structure using the command:

`data(result)`

if you follow the same column names of the predefined slots (data, metadata, predictions, etc, etc) to save your results, we cannot create a new element in the list. If what we want to save your results you need to format it to fit the predictions, modifications or modeling tables. Still, you can add things to the structure as long as you don't save it (using data(results) and only use it for visualization purposes.

2) Heavy computations preferably shouldn't be coded in Shiny but in an R function that you call, cgiarBase for your new functions, and any other CRAN package for simple calculations, and cgiarPipeline when you will use many lines and make a sort of pipeline function.

3) The run button needs to be the trigger to perform all the computations in an eventReactive where results are stored in an object. That object can then be used to build visualizations in the output tabs. The style parameters can be added to the output tabs as new input parameters that can be modified on the fly. Only the report is kind of a fixed format. The rest can be modified on the fly as the user explores the output tabs. I'll be happy to show you :) 

The trick is to modularize actions, the output tabs are only events that create a plot with the result from run. Functions should be modularized to quickly spot possible bugs :)  I hope this helps. Btw, the ddextend library keeps being loaded but only when the user clicks on the "Population Structure" tab in outputs. Maybe is a dependency of another library.
