### ISSUE TITLE
Multi-trait QA interface

### ISSUE THREAD

**Issue by covaruber** [Breeding-Analytics/bioflow#29]
Creating a ticket to follow up on the multi-trait QA interface :) would the end of Q2 be a realistic deadline?

**Comment by reyzaguirre** [comment]
I think it would be feasible for end Q2. From my side I would suggest to start by discussing the rules we are going to implement and conditions for the input data structure. I will share a sketch of how it works with potato and sweetpotato, so we can discuss how to make this more general for any crop.

**Comment by covaruber** [comment]
Thanks Raul, I guess the data input structure has to be the same than the other modules but I guess you are referring maybe to the input parameters of the function (which are the same than the interface).

+ Maybe the interface please asks for the traits to QA [we use a shinyWidget selectInput(..., multiple=TRUE) ]
+ From there we can display a table for the user to specify the range of valid values (interactive table where user writes the numeric values). 
+ The user clicks a run button that will call the function that identifies bad traits or records
+ The visualizations are just heat maps?

Sure, let us have a meeting, you show me how is normally conducted and we can find someone to build the interface you imagine and you build the internal function and  :) 

Cheers,
Eduardo

**Comment by reyzaguirre** [comment]
closing this as the interface is ready
