### ISSUE TITLE
Improvements to POPULATION STRUCTURE module

### ISSUE THREAD

**Issue by covaruber** [Breeding-Analytics/bioflow#8]
Here is my feedback on the population structure module. It looks great :) few suggestions:

1) Can we group some of the output visualizations? For example a) MDS-2D-plot and MDS-Table to just be a tab called MDS, b) Stat-Genotypes and Stat-Markers under a tab named Stats, c) can the summary-diversity and heatmap go together? We just have the graph presented first and the tables below or something like that :) just to avoid overwhelming the tab menu and grouping results.

2) I suggest the tables rendered are rounded for the numerical columns. You can see the DT::formatRound() function is used for that in several modules that display tables :) 

3) The dendrogram tab requires the ggtree package but I can't find it on CRAN, should this be installed from somewhere else? 

<img width="1249" alt="Screenshot 2024-03-08 at 8 21 48 AM" src="https://github.com/Breeding-Analytics/bioflow/assets/27698022/89172336-31c6-4bc3-b740-45257c4cbec3">

4) Also under Fst it seems that depending on wether the user selects to remove or not monomorphic markers they can get this error message:

<img width="1433" alt="Screenshot 2024-03-08 at 7 53 10 AM" src="https://github.com/Breeding-Analytics/bioflow/assets/27698022/f001f4a4-b847-4a64-8632-fcabe6af05ee">

5) The parameter for "add external groups" under the input, I suggest you add a sample data file that can be used in the current marker file from the G2F initiative. You can add that file with the other example files. It would be a cooked file but that way the users can download a sample file if they want to know what format should have. 

<img width="662" alt="Screenshot 2024-03-08 at 8 09 13 AM" src="https://github.com/Breeding-Analytics/bioflow/assets/27698022/f01a274c-5861-4813-ae9c-2bbe0d019cb6">

6) In the input parameters where the user could provide that additional table I would hide it in a box with a name like "Additional settings..." to make sure users do not think this is strictly necessary. Both the browse and the sample file. Only seen when the user explores a bit more.

<img width="628" alt="Screenshot 2024-03-08 at 8 11 50 AM" src="https://github.com/Breeding-Analytics/bioflow/assets/27698022/e3eb9ea9-0371-48d9-9cf3-3cd3c84180a5">

7) Internally consider calling the function from a package the following way

`clust  = cluster::agnes(mrdMAT, method = "ward")`

instead of:

```
library(cluster)
clust=agnes(mrdMAT, method = "ward")
```

8) I was wondering if we are storing any of these results in the structure? like in the metrics table things like Fst, AMOVA table, summaries and Stats should be stored in the object under metrics to allow the user to build and export a report easily.

9) Can we create an Rmd for a simpler report that includes some of the results? mostly summary statistics and some of the graphs :)

Congrats, it really looks like a great module :D thanks a lot Angela.

**Comment by RAngelaPG** [comment]
Thank you! I will work on that!

**Comment by covaruber** [comment]
Hi Angela, any update on these points? :) especially #7, seems that some methods are being overwritten by loading a library in the app. Thanks.

**Comment by RAngelaPG** [comment]
Hi Eduardo,

Yes, I change in my functions that issues now, and also I finish the changes in the population structure module, about the ggtree package I download from here: 

https://bioconductor.org/packages/release/bioc/html/ggtree.html

**Comment by covaruber** [comment]
Thanks a lot Angela, looks great :)
