### ISSUE TITLE
Improvements to PEDIGREE QA module

### ISSUE THREAD

**Issue by covaruber** [Breeding-Analytics/bioflow#9]
Can we add some graphs to guide the decision of users while selecting the input parameters? what simple graph or table can guide the right selection? 

<img width="1433" alt="Screenshot 2024-03-08 at 7 45 33 AM" src="https://github.com/Breeding-Analytics/bioflow/assets/27698022/c84f4766-f327-4c4b-9a51-bba909be8b81">

**Comment by RAngelaPG** [comment]
I already did it, I'm not sure if it wasn't updated correctly, I'm going to check it

**Comment by covaruber** [comment]
You are right :p my bad Angela, I didn't load the proper data. Thanks! :)
